src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * BOOKING
 *
 * @ORM\Table(name="booking")
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 */
class Booking
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;


    /**
     * @var string
     *
     * @ORM\Column(name="cleaning_type", type="string", length=255)
     */
    private $cleaningType;


    /**
     * @ORM\Column(type="datetime")
     */
    private $startTime;



    /**
     * @var string
     *
     * @ORM\Column(name="address", type="string", length=2048)
     */
    private $address;


    /**
     * @var integer
     *
     * @ORM\Column(name="number_of_square_meters", type="integer", length=255)
     */
    private $numberOfSquareMeters;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="App\Entity\Work", mappedBy="booking", cascade={"persist", "remove"})
     */
    private $work;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $review;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isGood;



    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     */
    private $user;

    public function __construct()
    {
        $this->work = new ArrayCollection();

    }

    /**
     * @param mixed $isGood
     * @return Booking
     */
    public function setIsGood($isGood)
    {
        $this->isGood = $isGood;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getisGood()
    {
        return $this->isGood;
    }

    /**
     * @param mixed $review
     * @return Booking
     */
    public function setReview($review)
    {
        $this->review = $review;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getReview()
    {
        return str_repeat("<i class='far fa-star'></i>", $this->review);
        // return $this->review;
    }

    /**
     * @param string $name
     * @return Booking
     */
    public function setName(string $name): Booking
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param string $cleaningType
     * @return Booking
     */
    public function setCleaningType(string $cleaningType): self
    {
        $this->cleaningType = $cleaningType;
        return $this;
    }

    /**
     * @return string
     */
    public function getCleaningType(): ?string
    {
        return $this->cleaningType;
    }


    public function setStartTime(\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;
        return $this;
    }


    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    /**
     * @param string $address
     * @return Booking
     */
    public function setAddress(string $address): Booking
    {
        $this->address = $address;
        return $this;
    }

    /**
     * @return string
     */
    public function getAddress(): ?string
    {
        return $this->address;
    }

    /**
     * @param int $numberOfSquareMeters
     * @return Booking
     */
    public function setNumberOfSquareMeters(int $numberOfSquareMeters): Booking
    {
        $this->numberOfSquareMeters = $numberOfSquareMeters;
        return $this;
    }

    /**
     * @return int
     */
    public function getNumberOfSquareMeters(): ?int
    {
        return $this->numberOfSquareMeters;
    }



    public function setWork(string $work): self
    {
        $this->work = $work;

        return $this;
    }


    public function getSessions()
    {
        return $this->work;
    }


    /**
     * @param $user
     * @return Booking
     */
    public function setUser($user): ?Booking
    {
        $this->user = $user;
        return $this;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Cleaning{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('vendor/font-awesome/css/fontawesome-all.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNav">
        <a class="navbar-brand" href="">
            {% if is_granted("ROLE_USER") %}
                {{ app.user.username }}
            {% endif %}
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ path('homepage') }}">Главная</a>
            </li>
            {% if is_granted("ROLE_USER") %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Профиль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('employee') }}">Сотрудники</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('booking') }}">Забронировать</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('app-schedule') }}">Расписание</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('app-booking-show') }}">Мои бронирования</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('fos_user_security_logout') }}">Выйти</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('employee') }}">Сотрудники</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('fos_user_registration_register') }}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('fos_user_security_login') }}">Войти</a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>
<div class="container pt-4">
    <div class="row">
        <div class="col mx-auto">
            {% set notices = app.flashes('notice') %}
            {% set errors = app.flashes('error') %}

            {% if notices %}
                {% for message in notices %}
                    <div class="notice">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            {% if errors %}

                {% for message in errors %}
                    <div class="error">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% block content %}{% endblock %}
        </div>
    </div>

</div>

{% block javascripts %}
    <script src="{{ asset('vendor/jquery/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ asset('vendor/popper/js/popper.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
{% endblock %}
</body>
</html>

templates/booking.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1>Забронировать чистку</h1>
            {% if form is not null %}
                {{ form(form) }}
            {% endif %}
        </div>
    </div>



{% endblock %}

templates/create_booking.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block content %}
    {% if form is not null %}
        {{ form(form) }}
    {% endif %}


{% endblock %}

templates/employee.html.twig
{% extends 'base.html.twig' %}

{% block title %} Сотрудники

{% endblock %}

{% block content %}
    <h1>Сотрудники компании</h1>

    {% for one_employee in employee %}

        <div class="module-page-item">
        <div class="row">
            <div class="col-md-9" style="text-align: center">

                <img class="card-img-top" style="width: 400px" src="{{ vich_uploader_asset(one_employee, 'imageFile') }}"/>

                <p style="font-size: 20px" class="module-page-name"> {{ one_employee.name }}  </p>

                <hr>

            </div>
        </div>






    {% endfor %}



{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Бронирования

{% endblock %}

{% block content %}
    <h1>Текущие брони</h1>

{% for one_booking in booking %}
<div class="module-page-item">
    <div class="row">
        <div class="col-md-9" style="text-align: center; border: 2px black solid">
            <h4>Наименование: </h4>
            <p style="font-size: 20px" class="module-page-name"> {{ one_booking.name }}  </p>
            <hr>
            <h4>Тип уборки: </h4>
            <p style="font-size: 20px" class="module-page-name"> {{ one_booking.cleaningType }}  </p>
            <hr>
            <h4>Адресс: </h4>
            <p style="font-size: 20px" class="module-page-name"> {{ one_booking.address }}  </p>
            <hr>
            <h4>Дата начала уборки: </h4>
            <p style="font-size: 20px" class="module-page-name">
            {{ one_booking.startTime|date('d') }}/
            {{ one_booking.startTime|date("m") }}/
            {{ one_booking.startTime|date('Y') }}
            </p>
            <hr>
            <h4>Количество квадратных метров: </h4>
            <p style="font-size: 20px" class="module-page-name"> {{ one_booking.numberOfSquareMeters }}  </p>

        </div>
    </div>
{% endfor %}




{% endblock %}

templates/mybooking.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block content %}
    <h1>Мои бронирования</h1>
    {% if bookings is not null %}
        <div class="row pb-2 pt-2 book-head">
            <div class="col-md-1">#</div>
            <div class="col-md-3">Адрес</div>
            <div class="col-md-2">Дата уборки</div>
            <div class="col-md-2">Успели</div>
            <div class="col-md-2">Рейтинг</div>
            <div class="col-md-2">Управление</div>
        </div>
        {% for booking in bookings %}
            <div class="row pb-1 pt-1 booking-cell">
                <div class="col-md-1">{{ booking.id }}</div>
                <div class="col-md-3">{{ booking.address }}</div>
                <div class="col-md-2">{{ booking.startTime | date("d.m.Y  H:i") }}</div>
                <div class="col-md-2">
                    {% if booking.isGood  == 1 %}
                        <i class="far fa-thumbs-up"></i>
                    {% endif %}
                    {% if booking.isGood  == 0 and booking.isGood is not null %}
                        <i class="far fa-thumbs-down"></i>
                    {% endif %}

                </div>
                <div class="col-md-2">{{ booking.review | raw }}</div>
                <div class="col-md-2">
                    {% if  booking.startTime > date("-2 days") %}
                        <a class="btn btn-danger"
                           href="{{ path('app_booking_remove' , {'id':booking.id} ) }}">Оменить</a>
                    {% endif %}
                    {% if  booking.startTime < date() %}
                        <a class="btn btn-success"
                           href="{{ path('app_review_booking',{'id': booking.id  }) }}">Оценить</a>
                    {% endif %}

                </div>

            </div>

        {% endfor %}

    {% endif %}


{% endblock %}

templates/schedule.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block content %}
    <h1>Расписание на 30 дней</h1>
    {% if bookings is not null %}
        <div class="row pb-2 pt-2 book-head">
            <div class="col-md-1">#</div>
            <div class="col-md-3">Адрес</div>
            <div class="col-md-2">Дата уборки</div>
            <div class="col-md-2">Сотрудники</div>
        </div>
        {% for booking in bookings %}
            <div class="row pb-1 pt-1 booking-cell">
                <div class="col-md-1">{{ booking.id }}</div>
                <div class="col-md-3">{{ booking.address }}</div>
                <div class="col-md-2">{{ booking.startTime | date("d.m.Y  H:i") }}</div>
                <div class="col-md-2">
                    {% for session in booking.sessions %}
                        {{ session.employee.name }}
                    {% endfor %}
                </div>

            </div>

        {% endfor %}

    {% endif %}


{% endblock %}